export {default as admin} from './admin'
export {default as auth} from './auth'
export {default as discount} from './discount'
export {default as user} from './user'
export {default as category} from './category'
export {default as upload} from './upload'
export {default as product} from './product'
export {default as order} from './order'