"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.order = exports.product = exports.upload = exports.category = exports.user = exports.discount = exports.auth = exports.admin = void 0;
var admin_1 = require("./admin");
Object.defineProperty(exports, "admin", { enumerable: true, get: function () { return __importDefault(admin_1).default; } });
var auth_1 = require("./auth");
Object.defineProperty(exports, "auth", { enumerable: true, get: function () { return __importDefault(auth_1).default; } });
var discount_1 = require("./discount");
Object.defineProperty(exports, "discount", { enumerable: true, get: function () { return __importDefault(discount_1).default; } });
var user_1 = require("./user");
Object.defineProperty(exports, "user", { enumerable: true, get: function () { return __importDefault(user_1).default; } });
var category_1 = require("./category");
Object.defineProperty(exports, "category", { enumerable: true, get: function () { return __importDefault(category_1).default; } });
var upload_1 = require("./upload");
Object.defineProperty(exports, "upload", { enumerable: true, get: function () { return __importDefault(upload_1).default; } });
var product_1 = require("./product");
Object.defineProperty(exports, "product", { enumerable: true, get: function () { return __importDefault(product_1).default; } });
var order_1 = require("./order");
Object.defineProperty(exports, "order", { enumerable: true, get: function () { return __importDefault(order_1).default; } });
