export {default as Home} from './Home'
export {default as Upload} from './Upload'
export {default as Product} from './Product'
export {default as ProductDetail} from './ProductDetail'
export {default as Cart} from './Cart'