export {default as Admins} from './Admins'
export {default as Discounts} from './Discounts'
export {default as Users} from './Users'
export {default as Categories} from './Categories'
export {default as Uploads} from './Uploads'