export {default as Admin} from './Admin'
export {default as Discount} from './Discount'
export {default as Categories} from './Categories'
export {default as User} from './User'
export {default as Upload} from './Upload'
export {default as Product} from './Product'